### ISSUE TITLE
New sensor setup won't save

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/Observations-Database#119]
Hi Tim,

I'm setting up some new sensors for stations where we've swapped out rain gauges. I've filled in the "Sensor detail" wizard and it says "Form is valid" but it doesn't save when I click on "Save". Any ideas?

![new sensor setup](https://user-images.githubusercontent.com/8395262/39704520-e2e61430-520b-11e8-9d00-6500d173f5cb.JPG)

**Comment by Abrisaeon** [comment]
This issue seems to have disappeared

**Comment by TimPN-SAEON** [comment]
Cool

Tim Parker-Nance
Senior Developer (Coastal)
Elwandle Coastal Node
South African Environmental Observation Network (SAEON) of the National
Research Foundation (NRF)
Ocean Sciences Campus, NMU, Gomery Avenue, Port Elizabeth
Tel: +27 41 504 4946 Cell: +27 72 141 7953
timpn@saeon.ac.za
www.saeon.ac.za

SAEON is a comprehensive, sustained, coordinated and responsive South
African environmental observation network that delivers long-term reliable
data for scientific research and informs decision-making for a knowledge
society and improved quality of life.

Hot off the press: Download the 2017 SAEON ANNUAL REPORT
<http://bit.ly/2v78RJ2>
