### ISSUE TITLE
Export format

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/Observations-Database#126]
Hi Tim,

I've noticed recently that the format for .csv exports has changed. It no longer arranges data in columns when you open it in Excel (image below). When I open in in Excel and try to save it as an xlsx file the format stays the same. 

The alternative, a download to Excel takes forever and it will take me days to respond to a data request using that.

Am I doing something wrong which causes everything to end up in one column?

![export csv](https://user-images.githubusercontent.com/8395262/40415685-c932115c-5e7b-11e8-8c98-bdd53df36890.JPG)

**Comment by Abrisaeon** [comment]
Never mind the change in csv export. All that's necessary are some extra steps in Excel (text to columns). I can advise the users accordingly.

**Comment by TimPN-SAEON** [comment]
Hi Abri. The CSV export format hasn't changed. Its a known issue with Excel. In the past you needed to set the default list separator in Control Panel, Region to colon (it defaults to semicolon). That now longer seems to work. The easiest way to force the csv import wizard to open is to open Excel and create a blank sheet. Then go to file Open, open the csv and the wizard should open. Make sure you check the comma delimiter, then it opens fine.
