### ISSUE TITLE
Assigning sensor start & end dates

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/Observations-Database#129]
Hi Tim,

I see you've been working on making the start and end dates more precise. I've used this on the Tierkloof 13B rain gauge where the Davis sensor was removed and a Texas gauge installed. I've assigned the end date for the Davis (correctly) as 16 Feb 2018 12:00. I even tried editing it and then filtering the data view to see the effect. It works beautifully!

However, when assigning the start date to the Texas gauge (JNHK_TIERK13B_RAIN_TX) as 16 Feb 2018 13:00 it seems to automatically use 17 Feb 2018 0:00 as the start. I tried editing this and filtering the data view but it doesn't respond as it should. 

Abri

**Comment by TimPN-SAEON** [comment]
Hi Abri

I have fixed the code and redid the import. Please double check and close this issue if you are happy.

Tim

**Comment by Abrisaeon** [comment]
Sorted! Thanks
