### ISSUE TITLE
Incorrect syntax error message

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/Observations-Database#131]
Hi Tim,

I'm trying to upload some data to our Langrivier fog stations at Jonkershoek. The file (data source), schema etc. has all remained exactly the same. My processing of the files have remained exactly the same (ie. copy the column headers to the row above the data and delete the " that the database doesn't like).

The same problem occurs whether I try to load the hourly or daily data. I've tried the 500 and 600 station - same story. I've tried copying the headers of previous successfully uploaded files into the new data files. That doesn't work either.

Any ideas?

I'm getting the message below:
![error](https://user-images.githubusercontent.com/8395262/42263130-6c141c8c-7f6d-11e8-8580-3622c80a61e2.JPG)

**Comment by TimPN-SAEON** [comment]
My bad, try again please

**Comment by Abrisaeon** [comment]
Sorted! Thank you.
