### ISSUE TITLE
Downloads only downloading column headers

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/Observations-Database#138]
Hi Tim,

As the title suggests...

This happens with .csv and excel downloads.

I discovered it when trying to download some Cathedral Peak Little Berg air temperature data for GWF Node.

**Comment by TimPN-SAEON** [comment]
Hi Abri, think I found the problem. Please try again and close if you are happy

**Comment by Abrisaeon** [comment]
Hi Tim,

The problem is still the same.

**Comment by TimPN-SAEON** [comment]
I am getting data from my tests. What station/instrument/sensor are you selecting?

**Comment by TimPN-SAEON** [comment]
Ok, I found the problem, please check again and close if you are happy

**Comment by Abrisaeon** [comment]
Thanks Tim, that seems to have solved the issue.

A new strange issue is that the dates in the csv are now all jumbled up and not in chronological order where in the past they were always as displayed in the data query. Should I open a new ticket for that?

**Comment by TimPN-SAEON** [comment]
Let me have a quick look

**Comment by TimPN-SAEON** [comment]
Ok, try now.

**Comment by Abrisaeon** [comment]
Perfect!
