### ISSUE TITLE
Sites missing and grouped under the wrong organizations

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/Observations-Database#139]
Hi Tim,

In trying to test whether the download issue has been resolved, I looked for Cathedral Peak again to navigate to the right sensors. Cathedral Peak is nowhere to be found.

It also seems like the SACTN stations are organized under just about every Organization that's been created. I assume this isn't right?

Is this a bug or did some user do go wild on the admin site?

**Comment by TimPN-SAEON** [comment]
Hi Abri

The SACTN are split across all those organisations. Of the 135 SACTN sites only 15 are actually SAEON's.

Will check the Cathedral Peak problem and get back to you.

**Comment by Abrisaeon** [comment]
That's a relief!

**Comment by Abrisaeon** [comment]
Thanks Tim, it's back in the list and I was able to navigate to the sensors I need. It's still only downloading the column headers but that's been logged as another issue so I'll close this.

I'd imagine the database will have to be set up so that data managers can see everything while only georeferenced sites are displayed on the query site. There are probably a few historical sites or farm rain gauges for which we don't have accurate location data.

Abri
