### ISSUE TITLE
Strange error message and no data

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/Observations-Database#144]
Hi Tim,

Not sure what's going on currently. I'm trying to do some uploads but can't see any data in any of my stations!!

Also, when looking for the data in the "import batches" observations tab, I get the message below:

![obs error 2 nov](https://user-images.githubusercontent.com/8395262/47907573-34f81600-de94-11e8-9373-7fcef8387e7e.JPG)

**Comment by TimPN-SAEON** [comment]
Sorry, database is busy being updated. Will let you know when its done

**Comment by TimPN-SAEON** [comment]
Update done, try again please
